require("options")
require("keymaps")
require("autocmds")
require("packages")
require("theme")

require("plugins.indent_blankline")
require("plugins.treesitter")
require("plugins.fzf_lua")
require("plugins.lsp")
