vim.pack.add({
    { src = "https://github.com/rebelot/kanagawa.nvim" },
    { src = "https://github.com/lukas-reineke/indent-blankline.nvim" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/ibhagwan/fzf-lua" },
    { src = "https://github.com/neovim/nvim-lspconfig"},
    { src = "https://github.com/rmagatti/auto-session" },
    { src = "https://github.com/Saghen/blink.cmp" },
    { src = "https://github.com/saghen/blink.lib" }, 
    { src = "https://github.com/stevearc/oil.nvim" },
    { src = "https://github.com/machakann/vim-sandwich" },
    { src = "https://github.com/Bekaboo/dropbar.nvim" },
    { src = "https://github.com/nvim-lualine/lualine.nvim" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
    { src = "https://github.com/windwp/nvim-autopairs" },
    { src = "https://github.com/Wansmer/treesj" },
    { src = "https://github.com/petertriho/nvim-scrollbar" },
    { src = "https://github.com/rachartier/tiny-inline-diagnostic.nvim" },
    { src = "https://github.com/rachartier/tiny-cmdline.nvim" },
    { src = "https://github.com/windwp/nvim-ts-autotag" },
    { src = "https://github.com/b0o/schemastore.nvim" },
    { src = "https://github.com/SmiteshP/nvim-navic" },
    { src = "https://github.com/MunifTanjim/nui.nvim" },
    { src = "https://github.com/hasansujon786/nvim-navbuddy" },
})
