"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ $os ](bg:#2a2a37 fg:#dcd7ba)\
$username\
$hostname\
$container\
[](bg:#363646 fg:#2a2a37)\
$directory\
[](fg:#363646 bg:#2b3328)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:#2b3328 bg:#252535)\
$nodejs\
${custom.typescript}\
$rust\
$golang\
$php\
[](fg:#252535)\
\n$character"""

right_format = "$cmd_duration"

[os]
disabled = false
format = "$symbol"

[os.symbols]
Windows = ""
Macos = ""
Linux = ""
Ubuntu = ""
CentOS = ""

[username]
style_root = "bold fg:#ff5d62 bg:#2a2a37"
style_user = "bold fg:#dcd7ba bg:#2a2a37"
show_always = true
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
format = '[$user ]($style)'

[hostname]
ssh_symbol = ""
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
style = "fg:#dcd7ba bg:#2a2a37"
format = '[via $ssh_symbol ($hostname) ]($style)'

[container]
symbol = ""
style = "fg:#dcd7ba bg:#2a2a37"
format = '[in $symbol ($name) ]($style)'

[directory]
style = "fg:#c8c093 bg:#363646"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "fg:#98bb6c bg:#2b3328"
format = '[ $symbol $branch ]($style)'

[git_commit]
only_detached = true
commit_hash_length = 7
tag_disabled = false
tag_symbol = ""
style = "fg:#98bb6c bg:#2b3328"
format = '[\($hash$tag\) ]($style)'

[git_state]
style = "fg:#e6c384 bg:#2b3328"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
rebase = "REBASE"
merge = "MERGE"
revert = "REVERT"
cherry_pick = "PICK"
bisect = "BISECT"
am = "AM"
am_or_rebase = "AM/REBASE"

[git_status]
style = "fg:#98bb6c bg:#2b3328"
format = '[$all_status$ahead_behind ]($style)'

conflicted = '[=](fg:#ff5d62 bg:#2b3328)'
modified = '[*](fg:#e82424 bg:#2b3328)'
deleted = '[✗](fg:#e82424 bg:#2b3328)'
staged = '[~](fg:#e6c384 bg:#2b3328)'
untracked = '[…](fg:#7fb4ca bg:#2b3328)'
stashed = '[\$](fg:#957fb8 bg:#2b3328)'
renamed = '[»](fg:#7fb4ca bg:#2b3328)'
ahead = '[+${count}](fg:#98bb6c bg:#2b3328)'
behind = '[-${count}](fg:#e6c384 bg:#2b3328)'
diverged = '[±+${ahead_count}-${behind_count}](fg:#ff5d62 bg:#2b3328)'
up_to_date = ''

[nodejs]
symbol = ""
style = "bg:#252535"
format = '[[ $symbol ($version) ](fg:#98bb6c bg:#252535)]($style)'

[rust]
symbol = ""
style = "bg:#252535"
format = '[[ $symbol ($version) ](fg:#ffa066 bg:#252535)]($style)'

[golang]
symbol = ""
style = "bg:#252535"
format = '[[ $symbol ($version) ](fg:#7fb4ca bg:#252535)]($style)'

[php]
symbol = ""
style = "bg:#252535"
format = '[[ $symbol ($version) ](fg:#957fb8 bg:#252535)]($style)'

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[ $duration](fg:#727169)"
